import React, { useEffect, useContext } from "react";
import Box from "../components/Box";
import girlicon from "../assets/girlicon.png";
import girlfood from "../assets/girl_food.jpeg";
import boy_exercise from "../assets/boy_exercise.avif";
import Navbar from "../components/Navbar";
import { useNavigate } from 'react-router-dom';
import { UserAuth } from "../contexts/AuthContext";

const Home = () => {
  const navigate = useNavigate();
  const { user } = UserAuth();

  useEffect(() => {
    if(!user) {
      navigate('/login');
    }
  }, [history, user]);

  return (
    <>
      <div>
       
        <div className="home">
          <Box
            page="endproduct"
            imageSrc={girlfood}
            altText="meal icon"
            title="Meal Tracking"
            description="Track your daily meals."
          />
          <Box
            page="ingredients"
            imageSrc={boy_exercise}
            altText="Activity Icon"
            title="Recipe Generator"
            description="Get a recipe generated by AI for yor available ingredients."
          />
          <Box
            page="stats"
            imageSrc={girlicon}
            altText="Stats Icon"
            title="Stats"
            description="View your health and fitness statistics."
          />
        </div>
      </div>
    </>
  );
};

export default Home;
